# TODO: Define the Workflow Name
name: CI pipeline

# TODO: Define triggers for the workflow
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # TODO: Define a job for building and testing the frontend
  frontend-test:
    runs-on: self-hosted
    defaults: 
      run: 
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node JS
      uses: actions/setup-node@v4.1.0
    - name: Install dependencies
      run: npm install
    - name: Run tests frontend
      run: echo "Testing frontend passed"
    #   run: npm test

  frontend-build:
    runs-on: self-hosted
    needs: frontend-test
    defaults: 
      run: 
        working-directory: frontend
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node JS
      uses: actions/setup-node@v4.1.0
    - name: Install dependencies
      run: npm install
    - name: Build React app
      run: npm run build
  
  
  # TODO: Define a job for building and testing the backend
  backend:
    runs-on: self-hosted
    defaults: 
      run: 
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.3.0
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r requirements.txt
      - name: Run tests backend
        run: python test_app.py
      # TODO: Checkout code
      # TODO: Setup Python
      # TODO: Install dependencies
      # TODO: Run tests

  # TODO: Define a job for building and pushing Docker images
  docker-fe:
    # Run this job only when 'frontend' & 'backend' stages are sucessfully completed
    needs: [frontend-build] 
    runs-on: self-hosted
    steps:
       -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
       -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
       -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
          name: Build and push frontend
          uses: docker/build-push-action@v6
          with:
            context: "{{defaultContext}}:frontend"
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopsfe:latest
      # TODO: Checkout code
      # TODO: Setup Docker
      # TODO: Build frontend Docker image
      # TODO: Build backend Docker image
      # TODO: Push images to Docker Hub (if on main branch)
  docker-be:
    # Run this job only when 'frontend' & 'backend' stages are sucessfully completed
    needs: [backend] 
    runs-on: self-hosted
    steps:
       -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
       -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
       -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
       - 
          name: Build and push backend
          uses: docker/build-push-action@v6
          with:
            context: "{{defaultContext}}:backend"
            push: true
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/devopsbe:latest
